# Generated by Django 4.1.2 on 2022-10-31 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'spr_activities_types',
            },
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'preval_coordinates',
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pereval_level',
            },
        ),
        migrations.CreateModel(
            name='ModerationStatus',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'moderation_status',
            },
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.TextField()),
                ('title', models.TextField()),
                ('other_titles', models.TextField()),
                ('connect', models.TextField(blank=True, null=True)),
                ('add_time', models.DateTimeField()),
                ('coord_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submitData.coords')),
                ('level_autumn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autumn_level', to='submitData.difficultylevel')),
                ('level_spring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spring_level', to='submitData.difficultylevel')),
                ('level_summer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summer_level', to='submitData.difficultylevel')),
                ('level_winter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winter_level', to='submitData.difficultylevel')),
                ('status', models.ForeignKey(default='new', on_delete=django.db.models.deletion.CASCADE, to='submitData.moderationstatus')),
            ],
            options={
                'db_table': 'pereval_added',
            },
        ),
        migrations.CreateModel(
            name='PerevalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.BigIntegerField()),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'pereval_areas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'pereval_users',
            },
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitData.pereval')),
            ],
            options={
                'db_table': 'pereval_images',
            },
        ),
        migrations.AddField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submitData.user'),
        ),
    ]
